### ISSUE TITLE
pip install - not working

### ISSUE THREAD

**Issue by frodrigo** [rezemika/oh_sanitizer#1]
After `pip install oh_sanitizer` I get only `venv3/lib/python3.4/site-packages/oh_sanitizer-0.1.0.dist-info` but no `venv3/lib/python3.4/site-packages/oh_sanitizer` with python code.
osm-fr/osmose-backend#312

**Comment by rezemika** [comment]
I just uploaded a `0.1.1` version, it should work now. ;)
